### ISSUE TITLE
Static private ip address assignment in ipconfiguration

### ISSUE THREAD

**Issue by sudhakar53** [cloudify-incubator/cloudify-azure-plugin#72]
Azure rest api expects the private ip address configuration inside 'properties tag' where as the plugin create the request body outside the properties.

[Expected:](https://docs.microsoft.com/en-us/rest/api/virtualnetwork/networkinterfaces/createorupdate) 
` "ipConfigurations": [
      {
         "properties": {
          "provisioningState": "Succeeded",
          "privateIPAddress": "172.20.2.4",
          "privateIPAllocationMethod": "Dynamic",
          "publicIPAddress": {
            "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/publicIPAddresses/test-ip"
          },
          "subnet": {
            "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/virtualNetworks/rg1-vnet/subnets/default"
          },
          "primary": true,
          "privateIPAddressVersion": "IPv4"
        }
      }
    ]`

Request body generated by plugin:
`'ipConfigurations': [{
    'privateIPAllocationMethod': 'Static',
    'name': 'vsinc_protected_ip_config',
    'privateIPAddress': '172.20.1.100',
    'properties': {
        'subnet': {
            'id': '/subscriptions/subid/resourceGroups/vfw-resources/providers/Microsoft.Network/virtualNetworks/private_vnet/subnets/protected_vsubnet'
        },
        'publicIPAddress': None
    }
}]`

This require small modification in ipconfiguration.py file to add the dict available in resource_config inside the properties tag.

**Comment by EarthmanT** [comment]
#73
